export const UI = {
  appName: 'מורה חכם',
  appSubtitle: 'מערכת תרגול חכמה לבגרות',
  login: 'כניסה',
  signup: 'הרשמה',
  username: 'שם משתמש',
  fullName: 'שם מלא',
  password: 'סיסמה',
  registerBtn: 'הרשמה',
  loginBtn: 'כניסה',
  logout: 'התנתקות',
  welcome: 'שלום',
  welcomeBack: 'ברוכים הבאים חזרה',
  addCourse: 'הוספת קורס חדש',
  selectCourse: 'בחר',
  editCourse: 'ערוך',
  deleteCourse: 'מחק',
  courseName: 'שם הקורס',
  courseNamePlaceholder: 'לדוגמה: מתמטיקה 5 יחידות',
  syllabusText: 'טקסט הסילבוס',
  parseSyllabus: 'נתח סילבוס',
  saveToDB: 'שמור לבסיס הנתונים',
  backToEdit: 'חזרה לעריכה',
  saveChanges: 'שמור שינויים',
  confirmReplace: 'אשר והחלף',
  reimportWarning: 'פעולה זו תמחק את כל הנתונים הקיימים של הקורס',
  inlineEdit: 'עריכה ישירה',
  reimport: 'ייבוא מחדש',
  subject: 'מקצוע',
  topic: 'נושא',
  subtopic: 'תת-נושא',
  total: 'סה״כ',
  completed: 'הושלמו',
  xp: 'XP',
  backToLobby: 'חזרה ללובי',
  phases: {
    iDo: 'אני מלמד',
    weDo: 'נתרגל ביחד',
    youDo: 'תרגול עצמאי',
  },
  iDoButton: 'הבנתי! בואו נתרגל ביחד',
  weDoButton: 'אני מוכן לתרגל לבד',
  weDoCaption: 'אפשר לשאול שאלות. אני אדריך אותך לפתרון בלי לתת את התשובה.',
  youDoCaption: 'נסה לפתור לבד. אפשר לבקש רמזים אם נתקעת.',
  hintsUsed: 'רמזים שנוצלו',
  expectedXp: 'XP צפוי',
  finalAnswer: 'התשובה הסופית שלך',
  submitAnswer: 'הגש תשובה',
  tryAgain: 'נסה שוב',
  gotXp: 'קיבלת',
  status: {
    not_started: 'לא התחיל',
    in_progress: 'בתהליך',
    completed: 'הושלם',
  },
  loading: 'טוען...',
  errorGeneric: 'אירעה שגיאה',
  registeredSuccess: 'נרשמת בהצלחה! כעת ניתן להתחבר.',
  passwordMinLength: 'הסיסמה חייבת להכיל לפחות 8 תווים',
  sendMessage: 'שלח הודעה',
  typeMessage: 'הקלד הודעה...',
  backToExplanation: 'חזרה להסבר',
} as const;

export function previewXp(hintsUsed: number): number {
  if (hintsUsed === 0) return 100;
  if (hintsUsed === 1) return 70;
  if (hintsUsed === 2) return 40;
  return 10;
}
